#  with using Dockerfile
version: "3.4"
services:
  beer_wiki_app:
    container_name: beer_wiki_app
    restart: always
    build:
      context: .
      target: 'develop'
    ports:
      - 8080:80
    volumes:
      - type: bind
        source: ./
        target: /app


